###=======================================category==============================
GET http://localhost:3000/admin/categories

###
POST http://localhost:3000/admin/category/store
Content-Type: application/json

{
    "title": "electronics",
    "logo": "http://placeimg.com/640/480",
    "status": "Inactive"
}
###
GET http://localhost:3000/admin/category/5f67a3e5f8a97808842f0c9a/show

###
PUT http://localhost:3000/admin/category/5f67a3e5f8a97808842f0c9a/update
Content-Type: application/json

{
    "title": "electronics",
    "logo": "http://placeimg.com/640/200",
    "status": "Active"
}

###
DELETE  http://localhost:3000/admin//category/5f67a3e5f8a97808842f0c9a/delete


###===========================================user======================================
GET http://localhost:3000/admin/users

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"rakibpiit@gmail.com",
    "password":"000"
}

### admin
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"rakib4",
    "password":"000"
}

### user
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"rakib",
    "password":"000"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "rakib4",
    "type":"admin",
    "email": "rakibpiit@gmail.com",
    "contact": "01111111111",
    "password": "000"
}

###
GET  http://localhost:3000/logout

